LingmoOS/lingmo-wiki

- docs/en/wiki/installation-guide.md
> Set lower storage limits

- docs/en/wiki/installation-guide.md
> feat: use ventoy instead of etcher

- README.md
> fix(README): replace pnpm with pnpx

- docs/en/wiki/faq.md
> feat(faq): archlingmo

- docs/en/wiki/faq.md
> fix(faq): broken link

- docs/en/wiki/build_lingmode.md
> feat: Build LingmoDE

- package-lock.json
- package.json
- pnpm-lock.yaml
> chore: lock

- docs/en/wiki/lingmo-terminal.md
- docs/en/wiki/list-of-lingmode-applications.md
> feat: lingmo-terminal

- docs/.vitepress/config/index.ts
- docs/.vitepress/config/zh.ts
- docs/en/index.md
- docs/zh/index.md
> feat: zh_CN locale

- docs/zh/index.md
> fix(zh): links

- docs/en/wiki/faq.md
> feat(faq): debian 12 packages

- docs/en/index.md
- docs/en/wiki/getting-started.md
> feat: getting-started

- docs/en/index.md
- docs/zh/index.md
> fix(index.md): getting-started links

- docs/en/wiki/lingmo-filemanager.md
> feat(lingmo-filemanager): desktop mode

- docs/en/wiki/getting-started.md
> chore(getting-started): remove spark

- docs/en/wiki/list-of-lingmode-applications.md
> feat: basic desktop components

- docs/en/wiki/faq.md
> feat(faq): migration from hydrogen to helium

- docs/.vitepress/config/index.ts
- docs/public/robots.txt
- [ y] The commit message follows our guidelines
- [ y] Tests for the changes have been added (for bug fixes / features)
- [ y] Docs have been added / updated (for bug fixes / features)
Feature
New: Add sitemap feature
> feat: add sitemap feature

- docs/en/wiki/installation-guide.md
> fix(installation-guide): typo

- docs/en/wiki/getting-started.md
- docs/en/wiki/installation-guide.md
> refactor: unify Lingmo OS

- docs/en/wiki/getting-started.md
> feat(getting-started): update introduction

- docs/zh/index.md
- docs/zh/wiki/getting-started.md
> refactor(zh): getting-started

- docs/en/wiki/installation-guide.md
> feat(installation-guide): add warning

- docs/en/wiki/lingmo-settings.md
> feat: lingmo-settings

- docs/en/wiki/develop-guide.md
> refactor: develop-guide

- docs/en/wiki/develop-guide.md
> feat(develop-guide): reporting a bug & manually compile LingmoDE

- docs/en/wiki/list-of-lingmode-applications.md
> feat: add lingmo-settings link

- README.md
> style: reformat README.md

- docs/zh/wiki/lingmo-filemanager.md
- docs/zh/wiki/lingmo-terminal.md
> fix(zh): unify `gallery`

- docs/zh/wiki/develop-guide.md
> refactor(zh/develop-guide): sync from en

- docs/en/index.md
> refactor: index

- docs/zh/wiki/lingmo-settings.md
> feat(zh): lingmo-settings

- docs/en/wiki/glossary.md
> refactor(en/glossary): use abbr.

- docs/zh/wiki/glossary.md
> refactor(zh): glossary

- docs/en/wiki/glossary.md
> feat(glossary): update related information about ArchLingmo

- docs/zh/wiki/glossary.md
> feat(zh/glossary): sync from English wiki

- docs/en/wiki/faq.md
> refactor(faq): archlingmo

- docs/en/wiki/installation-guide.md
> refactor: installation-guide

- docs/en/index.md
- docs/en/wiki/tutorial.md
- docs/en/wiki/tutorials.md
> fix: remove tutorial.md

- docs/en/wiki/installation-guide.md
> fix(installation-guide.md): fix download link

- docs/en/wiki/history.md
> feat(history): add todo

- docs/en/wiki/faq.md
> refactor(faq): remove debian 13 selection

- docs/en/wiki/manual-of-style.md
> feat: manual of style

- docs/en/wiki/glossary.md
> feat: update LingmoNix project links

- docs/en/wiki/develop-guide.md
> feat: add deprecation warning

- docs/en/wiki/tutorials.md
- docs/zh/wiki/tutorials.md
> feat(zh/tutorials): sync from en

- docs/zh/wiki/tutorials.md
> fix: add translation

- docs/en/wiki/about-wiki.md
> feat: complete about-wiki structure

- docs/en/wiki/glossary.md
- [xp] The commit message follows our guidelines
> feat(glossary): rename Lingmo-Archive to LingmoOS-Archive

- docs/zh/wiki/glossary.md
> feat(zh/glossary): update links

- docs/zh/wiki/component-list.md
> feat(zh): remove kernel

- docs/zh/wiki/faq.md
- [v ] The commit message follows our guidelines
- [v] Tests for the changes have been added (for bug fixes / features)
- [v] Docs have been added / updated (for bug fixes / features)
> Fix: Delete outdated FAQ information
